name: Deploy WordPress

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker run --name wordpress -p 80:80 -d wordpress:latest
        docker ps -a

    - name: Wait for WordPress to be ready
      run: sleep 30  # Adjust as necessary for WordPress to initialize

    - name: Verify WordPress is running
      run: curl -I http://localhost

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # Branch to deploy to
        publish_dir: ./  # Replace with the directory you want to deploy
